services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  jenkins-agent:
    build:
      context: .
      dockerfile: dockerfile.jenkins-agent
    user: root
    privileged: true
    container_name: jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_data:/var/jenkins/agent
    depends_on:
      - jenkins
    env_file:
      - .env

  db:
    image: postgres:16
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopzen
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/shopzen
      FRONTEND_URL: http://localhost:3000 # For CORS

  backend-tests:
    build: ./backend
    command: pytest --disable-pytest-warnings
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/shopzen

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  selenium:
    image: seleniarm/standalone-chromium:latest
    # image: selenium/standalone-chromium:latest // Use this line instead for x86_64 systems
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    depends_on:
      - frontend
    environment:
      - NODE_ENV=production # This will make Next.js use .env.production

  e2e-tests:
    build:
      context: ./frontend
    command: >
      sh -c "
      echo '⏳ Waiting for frontend and selenium...' &&
      until nc -z selenium 4444; do sleep 1; done &&
      echo '✅ Services ready!' &&
      IN_DOCKER=true node tests/e2e/selenium-add-to-cart.test.js
      "
    depends_on:
      - selenium
      - frontend
    environment:
      - NODE_ENV=test
      - IN_DOCKER=true

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  analytics:
    build: ./analytics
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/shopzen

volumes:
  db_data:
  jenkins_data:
  prometheus_data:
  grafana_data:
