global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:3000"]
